DROP TABLE los_desnormalizados.Viaje_x_paquete, 
	los_desnormalizados.Material_x_tarea,
	los_desnormalizados.Viaje,
	los_desnormalizados.Material,
	los_desnormalizados.Chofer,
	los_desnormalizados.Tarea_x_orden,
	los_desnormalizados.Orden_trabajo,
	los_desnormalizados.Estado,
	los_desnormalizados.Tarea,
	los_desnormalizados.Tipo_tarea,
	los_desnormalizados.Paquete,
	los_desnormalizados.Tipo_paquete,
	los_desnormalizados.Camion,
	los_desnormalizados.Modelo,
	los_desnormalizados.Marca,
	los_desnormalizados.Recorrido,
	los_desnormalizados.Mecanico,
	los_desnormalizados.Taller,
	los_desnormalizados.Ciudad

