DROP TABLE gd_esquema.Viaje_x_paquete, 
	gd_esquema.Material_x_tarea,
	gd_esquema.Viaje,
	gd_esquema.Material,
	gd_esquema.Chofer,
	gd_esquema.Tarea_x_orden,
	gd_esquema.Orden_trabajo,
	gd_esquema.Estado,
	gd_esquema.Tarea,
	gd_esquema.Tipo_tarea,
	gd_esquema.Paquete,
	gd_esquema.Tipo_paquete,
	gd_esquema.Camion,
	gd_esquema.Modelo,
	gd_esquema.Marca,
	gd_esquema.Recorrido,
	gd_esquema.Mecanico,
	gd_esquema.Taller,
	gd_esquema.Ciudad

